@startuml
title Módulo: Gestión de Archivos

rectangle "Front-End (UI)" {
  [Carga de Archivos]
  [Validación Visual]
}

rectangle "Back-End (Lógica)" {
  [ArchivoController]
  [StorageService]
  [ValidationService]
}

note right of [ArchivoController]
  Roles habilitados:
  * CLIENTE/AUDITOR: subir y validar
  * ADMIN: supervisión
end note

database "Base de Datos" {
  [audit_requests]
  [audit_log]
}

[Carga de Archivos] --> [ArchivoController] : POST /audits
[ArchivoController] --> [StorageService]
[ArchivoController] --> [audit_requests]
[ValidationService] --> [audit_log]

@enduml
